import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Homepage from './components/Homepage'
import Navigationbar from './components/Navbar'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Kryptomania</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <Navigationbar />
       <Homepage />
      </main>

    </div>
  )
}
